apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: dev1
spec:
  limits:
    - default:
        memory: 512Mi
        cpu: 1
      defaultRequest:
        cpu: 0.5
        memory: 256Mi
      max:
        memory: 1Gi
        cpu: 4
      min:
        memory: 128Mi
        cpu: 0.5
      type: Container