apiVersion: v1
kind: LimitRange # es nivel de namespace
metadata:
  name: recursos
spec:
  limits:
    - default:
        memory: "512Mi" #cualquier recurso que no indique la memoria tomara los valores default
        cpu: 1
      defaultRequest:
        memory: "256Mi"
        cpu: 0.5
      max:
        memory: "1Gi" #dara un error si el pod supera el max o es menos del min
        cpu: 4
      min:
        memory: "128Mi"
        cpu: 0.5
      type: Container # tambien puede tomar valor pod, y toma sentido si tiene varios container dentro, se suman los
      #recursos de los contenedores, y el total no debe superar el max