apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-d
  labels:
    version: v1
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
      nodeSelector:
        app: dev1
