apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-2
  namespace: dev1
  labels:
    app: mysql-2
    type: db
spec:
  selector:
    matchLabels:
      app: mysql-2
      type: db
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-2
        type: db
    spec:
      containers:
      - name: mysql-2
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: MYSQL_DATABASE
        ports:
          - containerPort: 3306
            name: db-port
