#deployment de prueba para crearlo en un namespace
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic
  labels:
    tipo: desarrollo
spec:
  selector: #permite seleccionar un conjunto de objetos que cumplan las condiciones
    matchLabels:
      app: elastic
  replicas: 2
  strategy:
    type: RollingUpdate
  minReadySeconds: 2
  template: #plantilla que define los containers
    metadata:
      labels:
        app: elastic
    spec:
      containers:
      - name: elastic
        image: elasticsearch:7.6.0
        ports:
        - containerPort: 9200